version: "2"
services:


    # MySQL 5.7: https://hub.docker.com/_/mysql/
    mysql:
        container_name: mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "lqh5879412"
            MYSQL_USER: "lqh"
            MYSQL_PASSWORD: "lqh5879412"
            MYSQL_DATABASE: "huishima_m"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /home/docker/mysql:/var/lib/mysql
        ports:
            - "13306:3306"
    # Redis 3.2.10: https://hub.docker.com/_/redis/
    redis:
        container_name: redis
        image: redis:3.2.10
        volumes:
            - /home/docker/redis:/data
        ports:
            - "16379:6379"
    huishima-api:
        container_name: huishima-api
        image: mynpf
        hostname: huishima-api
        links:
            - mysql
            - redis
        volumes:
            - /home/lqh/projects/hsmapi:/var/www/html
        ports:
            - "5221:8081"


    phper:
            container_name: phper
            image: sdbase
            hostname: phper
            links:
                - mysql
                - redis
            volumes:
                - /etc/localtime:/etc/localtime:ro
                - /home/lqh/projects/phper:/apps
            ports:
                - "7225:8004"



    huishima-admin:
        container_name: huishima-admin
        image: myapache
        hostname: huishima-admin
        links:
            - mysql
            - redis
        volumes:
            - /home/lqh/projects/huishima-admin:/app/public
        ports:
            - "8080:80"

