version: "2"
services:
    #influxdb server
    influxdb:
        image: influxdb:1.5.2-alpine
        container_name: influxdb
        volumes: 
          - /etc/localtime:/etc/localtime:ro
          - influxdb_data:/var/lib/influxdb
        ports:
          - "18083:8083"
          - "18086:8086"
          - "18090:8090"

    # MongoDB: https://hub.docker.com/_/mongo/
    mongodb:
        image: mongo:3
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - mongo_data:/data/db
      # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docker.html
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - es_data:/usr/share/elasticsearch/data
        environment:
          - http.host=0.0.0.0
          - transport.host=localhost
          - network.host=0.0.0.0
          # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
          - xpack.security.enabled=false
          - "ES_JAVA_OPTS=-Xms512m -Xmx1g"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        mem_limit: 1g
    # Graylog: https://hub.docker.com/r/graylog/graylog/
    graylog:
        image: graylog/graylog:2.4.3-1
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /home/lqh/docker-yml/swoole-docker/DEV/graylog.conf:/usr/share/graylog/data/config/graylog.conf
          - graylog_journal:/usr/share/graylog/data/journal
        environment:
          # CHANGE ME!
          - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
          # Password: admin
          - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
          - GRAYLOG_WEB_ENDPOINT_URI=http://www.edaoduo.com:9000/api
        links:
          - mongodb:mongo
          - elasticsearch
        depends_on:
          - mongodb
          - elasticsearch
        ports:
          # Graylog web interface and REST API
          - 9000:9000
          # Syslog TCP
          - 514:514
          # Syslog UDP
          - 514:514/udp
          - 5555:5555/udp
          # GELF TCP
          - 12201:12201
          # GELF UDP
          - 12201:12201/udp


    # MySQL 5.7: https://hub.docker.com/_/mysql/
    mysql:
        container_name: mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "aoduo"
            MYSQL_PASSWORD: "aoduo168"
            MYSQL_DATABASE: "aoduo"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /home/docker/mysql:/var/lib/mysql
        ports:
            - "13306:3306"
    #mqtt server
    mqtt:
        container_name: mymqtt
        image: toke/mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
        entrypoint: /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
        volumes:
            - /home/lqh/docker-yml/swoole-docker/DEV/mosquitto.conf:/etc/mosquitto/mosquitto.conf
            - /home/lqh/docker-yml/swoole-docker/DEV/websockets.conf:/etc/mosquitto/conf.d/websockets.conf
#command: bash -c "/usr/sbin/mosquitto"

# kafka:
#      container_name: mykafka
#      image: wurstmeister/kafka
#      ports:
#          - "9092:9092"
#      command: bash -c "cd /opt/kafka/ &&  bin/zookeeper-server-start.sh -daemon config/zookeeper.properties && bin/kafka-server-start.sh config/server.properties"
    # Redis 3.2.10: https://hub.docker.com/_/redis/
    redis:
        container_name: redis
        image: redis:3.2.10
        volumes:
            - /home/docker/redis:/data
        ports:
            - "16379:6379"

    redis-test:
        container_name: redis-test
        image: redis:3.2.10
        volumes:
            - /home/docker/redis-test:/data
        ports:
            - "16378:6379"


    redis_manager: 
        container_name: redis_manager
        image: erikdubbelboer/phpredisadmin
        links:
            - redis
        environment:
            - REDIS_1_HOST=redis
            - REDIS_1_NAME=MyRedis
            - ADMIN_USER=admin
            - ADMIN_PASS=admin87958
        ports:
            - "16380:80"

    # SD框架阿里云内网registry-internal.cn-hangzhou.aliyuncs.com/youwoxing/dev
    aoduo:
        container_name: aoduo
        image: mynpf
        hostname: aoduo
        links:
            - mysql
            - redis
        volumes:
            - /home/lqh/projects/aoduo:/var/www/html
        ports:
            - "5221:8081"
            - "5223:8019"
            - "5224:8020"
            - "5222:8000"
            - "5212:8282"
            - "5211:8383"
            - "5241:8082"
            - "5226:8021"
            - "5227:8022"


    devsd:
            container_name: devsd
            image: sd3base
            hostname: devsd
            links:
                - mysql
                - redis
                - nats
            volumes:
                - /etc/localtime:/etc/localtime:ro
                - /home/lqh/projects/dev-base/bus_plat/sd:/apps
                - /home/lqh/projects/dev-base:/var/www/html
                - /home/lqh/docker-yml/swoole-docker/DEV/devsd.conf:/etc/nginx/sites-enabled/devsd.conf
                - /home/lqh/docker-yml/swoole-docker/DEV/devsd-nginx.conf:/etc/nginx/nginx.conf
            ports:
                - "7225:8004"
                - "7226:8022"
                - "7241:8082"
#            entrypoint: ["nginx"]



    devsd-test:
            container_name: devsd-test
            image: sd3base
            hostname: devsd-test
            links:
                - mysql
                - redis-test
                - nats
            volumes:
                - /etc/localtime:/etc/localtime:ro
                - /home/lqh/projects-test/dev-base/bus_plat/sd:/apps
            ports:
                - "7125:8004"
                - "7126:8022"
                - "7141:8082"



    aod_devsd:
            container_name: aod_devsd
            image: sd3base
            hostname: aod_devsd
            links:
                - mysql
                - redis
                - nats
                - influxdb
            volumes:
                - /etc/localtime:/etc/localtime:ro
                - /home/lqh/projects/aoduo/bus_plat/aod-devsd:/apps
            ports:
                - "7135:8004"


    aod_devsd-test:
            container_name: aod_devsd-test
            image: sd3base
            hostname: aod_devsd-test
            links:
                - mysql
                - redis-test
                - nats
                - influxdb
            volumes:
                - /etc/localtime:/etc/localtime:ro
                - /home/lqh/projects-test/aoduo/bus_plat/aod-devsd:/apps
            ports:
                - "7235:8004"
                
#    command: bash -c "nginx"
#command: "nginx"

    # SD框架阿里云内网registry-internal.cn-hangzhou.aliyuncs.com/youwoxing/dev
    aoduo-test:
        container_name: aoduo-test
        image: mynpf
        hostname: aoduo-test
        links:
            - mysql
            - redis-test
        volumes:
            - /home/lqh/projects-test/aoduo:/var/www/html
        ports:
            - "6221:8081"
            - "6223:8019"
            - "6224:8020"
            - "6222:8000"
            - "6212:8282"
            - "6211:8383"
            - "6241:8082"
            - "6226:8021"
            - "6227:8022"

    nats:
            container_name: nats_sd
            image: nats
            hostname: nats
            ports:
                - "18222:8222"
                - "14222:4222"
                - "16222:6222"    

    
    caixx:
            container_name: caixx
            image: tutum/apache-php
            hostname: caixx
            links:
                - mysql
            volumes:
                - /opt/cxx/www:/app
            ports:
                - "6180:80"

# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
     mongo_data:
          driver: local
     es_data:
          driver: local
     influxdb_data:
          driver: local
     graylog_journal:
          driver: local            
